### ISSUE TITLE
use_strict check should ignore Perl 6 modules.

### ISSUE THREAD

**Issue by niner** [cpants/Module-CPANTS-Analyse#28]
The Inline::Perl6 module contains a small Perl 6 helper module:
https://metacpan.org/source/NINE/Inline-Perl6-0.07/lib/Inline/Perl6/Helper.pm

CPANTS::Analyse incorrectly complains about a missing "use strict":
https://metacpan.org/source/NINE/Inline-Perl6-0.07/lib/Inline/Perl6/Helper.pm

It should stop analysing when encountering a use v6; or use v6.c or similar. Bonus points for recognizing even use v6-inline;

**Comment by charsbar** [comment]
Thanks for spotting this. Perl 6 distributions have already been skipped, but a Perl 6 module in a Perl 5 distribution is not skipped. Let me know if there's anything we should also skip for such a module.
