### ISSUE TITLE
xt/kwalitee/has_meta_json.t missing from dist

### ISSUE THREAD

**Issue by pghmcfc** [cpants/Module-CPANTS-Analyse#38]
xt/kwalitee/has_meta_json.t is not included in the 0.99 release, which results in xt/kwalitee.t failing if you try to run it (which I did because there were quite a lot of changes since 0.96 and I wanted to test it as much as possible). Copying in the file from the github repo was sufficient to get it working for me.

**Comment by charsbar** [comment]
Thanks. Files under xt are not bundled in the distribution anymore.
