### ISSUE TITLE
t\analyse\manifest.t failure on Windows

### ISSUE THREAD

**Issue by jddurand** [cpants/Module-CPANTS-Analyse#43]
With perl 5.37.6 on recent Windows, the symlink test is failing, c.f. briandfoy/test-file#36 to better explanation. A possible fix is to be able to use Test::File::has_symlinks function as of version 1.993 of the later.

```
t\analyse\manifest.t ..... 1/?
#   Failed test 'symlinks not listed in MANIFEST is not ignored for a non-local distribution'
#   at t\analyse\manifest.t line 77.
# Looks like you failed 1 test of 14.
```

**Comment by charsbar** [comment]
Fixed by #50
