### ISSUE TITLE
New metric: level of backwards compatibility

### ISSUE THREAD

**Issue by grr** [cpants/Module-CPANTS-Analyse#45]
Players should get more points for the number of stable perl versions on which their dist works. I'm seeing more authors releasing dists with minimum required perl version that are unnecessarily high either because they don't know better or to reduce maintenance burden. The minimum required perl version should also not be lower than that found from the prereqs- i.e. if A states min as 5.20, but has a prereq of B with a min of 5.32, then A should have a min of at least 5.32.

See also: https://github.com/metacpan/metacpan-web/issues/2911

**Comment by charsbar** [comment]
The first part (getting more points for the number of stable perl versions) discourages people who use better perls with good reasons. The second part is not what an author can control because the prereqs may require better perls at any time.
